version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: veilgate
    main: ./cmd/veilgate
    binary: veilgate
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: veilgate
    name_template: "veilgate_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - configs/veilgate.yaml

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: C0oki3s
    name: veilgate
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
